spring.application.name=studenttask

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=akst01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true